// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

namespace GTCore.ViewModel
{
    public class CensusTeam
    {
        public string Type;
        public int? Surveyor_ID; 
        public string Reference_No;
        public string Title;
        public string District;
    }
}